cars = ['bmw', 'audi', 'toyota', 'subaru']
print("Here is the original list:")
print(cars)
print("\nHere is the sorted list:")
new_list = sorted(cars, reverse = True)
print(new_list)
print("\nHere is the original list again:")
print(cars)
print("\n")
print("\nThe reversed car list is: ")
reversed_cars = cars.copy()
reversed_cars.reverse()
print(reversed_cars)
print("\nHere is the original list again:")
print(cars)
print(len(cars))